gui:
  theme:
    searchingActiveBorderColor:
      - "#fab388"
      - "bold"
    optionsTextColor:
      - "#89b4fb"
    inactiveBorderColor:
      - "#89b4fb"
    defaultFgColor:
      - "#cdd6f5"
    cherryPickedCommitFgColor:
      - "#89b4fb"
    cherryPickedCommitBgColor:
      - "#f2cdce"
    activeBorderColor:
      - "#fab388"
      - "bold"
    unstagedChangesColor:
      - "#f38ba9"
    selectedLineBgColor:
      - "#45475b"

  authorColors:
    '*': '#b4befe'
  nerdFontsVersion: "3"
