"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
$directory$git_branch$git_status
$character
"""

right_format = """
$conda$python
"""

# Left side
[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
style = 'bold blue'
read_only = ' '
read_only_style = 'red'

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style): '
symbol = ' '
style = 'bold text'
truncation_length = 10 
truncation_symbol = "…"

[git_status]
format = '[$ahead$behind$diverged$conflicted$untracked$modified$renamed$staged$deleted]($style)'
style = 'text'

ahead = '[ ${count}](green)'
behind = '[ ${count}](red)'
diverged = '[ ${ahead_count}  ${behind_count}](yellow)'

conflicted = '[ ${count}](yellow) '
untracked = '[?${count}](text) '
modified = '[~${count}](peach) '
renamed = '[+${count}](blue) '
staged = '[+${count}](green) '
deleted = '[-${count}](red) '

# Right side
[conda]
format = '[$symbol$environment]($style) '
symbol = ' '
style = 'green'
ignore_base = false

[python]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = 'yellow bold'

[nix_shell]
symbol = ' '

# Catpuccin mocha color palette
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
